db0:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://120.25.73.72:3306/sharding_jdbc_0
  username: xiaobing
  password: 8541868
db1:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://120.25.73.72:3306/sharding_jdbc_1
  username: xiaobing
  password: 8541868

